title: Connor J. McWard

logo: /assets/img/PFP.jpg

author:
  name: Connor J. McWard
  email: cmcward@berkeley.edu

contact:
  phone: 408-833-4721
  email: cmcward@berkeley.edu
  linkedin: https://linkedin.com/in/connormcward
  

description: | 
  I am a data scientist who is passionate about applying machine learning and statistical analysis to solve complex and   novel problems in business, astrophysics, and physics. I am motivated by the challenge of discovering new insights and patterns from large and diverse datasets, and I value collaboration, innovation, and curiosity in my work.

  <p>
  Email: cmcward@berkeley.edu
  Phone: (408) 833-4721
  [LinkedIn](https://linkedin.com/in/connormcward) 
  </p>



# show_downloads: true
theme: jekyll-theme-minimal
